on:
  push:
    branches:
      - '*'
  schedule:
    - cron: "0/20 * * * *"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Webots Action Test
      id: hello
      uses: DavidMansolino/webots-action-test@R2020b-rev1
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
