name: Action Test

on:
  push:
    branches:
      - '*'
  # schedule:
  #   - cron: "*/10 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to print Webots version
    steps:
    - id: webots_step
      uses: DavidMansolino/webots-action-test@master
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output Webots version
      run: echo "The version was ${{ steps.webots_step.outputs.time }}"
