on:
  push:
    branches:
      - '*'
  schedule:
    - cron: "0/20 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to print Webots version
    steps:
    - id: webots_step
      uses: DavidMansolino/webots-action-test@R2020b-rev1
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output Webots version
      run: echo "The version was ${{ steps.hello.webots_step.time }}"
