name: Container Test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step1.outputs.version }}
    container:
      image: cyberbotics/webots:latest
    steps:
    - name: Get Webots Version
      run: |
        xvfb-run webots --version --batch
        export VERSION="R2020b revision 1"
        echo $VERSION
        echo "::set-output name=version::$VERSION"
    - name: Get Sysinfo
      run: xvfb-run webots --sysinfo --batch
