name: Container Test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step1.outputs.version }}
    container:
      image: cyberbotics/webots:latest
    steps:
    - name: Print Webots Version
      run: |
        xvfb-run webots --version --batch
    - name: Print System Information
      run: xvfb-run webots --sysinfo --batch
